import { Fragment } from "react";

import Head from "next/head";

import { Provider } from "react-redux";
import store from "../store/index";

import "../styles/globals.css";
import NavigationBar from "../components/navigation-bar/navigation-bar";
import Footer from "../components/footer/footer";

function MyApp({ Component, pageProps }) {
  return (
    <Provider store={store}>
      <Head>
        <title>Ajio Clone</title>
        <meta
          name="description"
          content="Generated by create next app"
          width={100}
          height={50}
        />
        <link rel="icon" href="/favicon.ico" />
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
      </Head>
      <NavigationBar />
      <div
        style={{
          minHeight: "100vh",
          display: "grid",
          gridTemplateColumns: "auto 1fr",
          gridTemplateRows: "96px 1fr auto",
        }}
      >
        <div
          style={{
            gridRowStart: "2",
            gridRowEnd: "3",
          }}
        >
          <Component {...pageProps} />
        </div>
        <div
          style={{
            gridRowStart: "3",
          }}
        >
          <Footer />
        </div>
      </div>
    </Provider>
  );
}

export default MyApp;
